# Generated by Django 3.1.1 on 2020-12-30 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_listmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 11, 17, 11, 878270)),
        ),
        migrations.AlterField(
            model_name='shopping_listmodel',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 11, 17, 11, 878334)),
        ),
    ]
