# Generated by Django 3.1.3 on 2020-11-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_shopping_listmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_listmodel',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
