# Generated by Django 3.1.3 on 2020-11-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_shopping_listmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_listmodel',
            name='list_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
