# Generated by Django 3.1.3 on 2020-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20201206_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_listmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shopping_listnamemodel',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
